/opt/ros/noetic/share/genmsg/cmake/pkg-genmsg.cmake.em:56: error: <class 'genmsg.base.InvalidMsgSpec'>: Duplicate field names in message: ['set_dock_state', 'set_dock_state']
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/em.py", line 3302, in <module>
    if __name__ == '__main__': main()
  File "/usr/lib/python3/dist-packages/em.py", line 3300, in main
    invoke(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/em.py", line 3283, in invoke
    interpreter.wrap(interpreter.file, (file, name))
  File "/usr/lib/python3/dist-packages/em.py", line 2295, in wrap
    self.fail(e)
  File "/usr/lib/python3/dist-packages/em.py", line 2284, in wrap
    callable(*args)
  File "/usr/lib/python3/dist-packages/em.py", line 2359, in file
    self.safe(scanner, done, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2421, in parse
    token.run(self, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/lib/python3/dist-packages/em.py", line 2595, in execute
    _exec(statements, self.globals, locals)
  File "<string>", line 48, in <module>
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/deps.py", line 70, in find_srv_dependencies_with_type
    spec = genmsg.msg_loader.load_srv_from_file(msg_context, msg_file, full_type_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/msg_loader.py", line 485, in load_srv_from_file
    spec = load_srv_from_string(msg_context, text, full_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/msg_loader.py", line 469, in load_srv_from_string
    msg_in = load_msg_from_string(msg_context, text_in.getvalue(), '%sRequest'%(full_name))
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/msg_loader.py", line 269, in load_msg_from_string
    spec = MsgSpec(types, names, constants, text, full_name, package_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/msgs.py", line 251, in __init__
    raise InvalidMsgSpec("Duplicate field names in message: %s"%names)
genmsg.base.InvalidMsgSpec: Duplicate field names in message: ['set_dock_state', 'set_dock_state']
[31m[1mCMake Error[0m at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/home/avinaash/daimler_tugger/doozy_ws/build/daimler_tugger/catkin_generated/env_cached.sh
  "/usr/bin/python3" "/usr/lib/python3/dist-packages/em.py" "--raw-errors"
  "-F"
  "/home/avinaash/daimler_tugger/doozy_ws/build/daimler_tugger/cmake/daimler_tugger-genmsg-context.py"
  "-o"
  "/home/avinaash/daimler_tugger/doozy_ws/build/daimler_tugger/cmake/daimler_tugger-genmsg.cmake"
  "/opt/ros/noetic/share/genmsg/cmake/pkg-genmsg.cmake.em") returned error
  code 1
[36mCall Stack (most recent call first):[0m
  /opt/ros/noetic/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
  /opt/ros/noetic/share/genmsg/cmake/genmsg-extras.cmake:303 (em_expand)
  CMakeLists.txt:71 (generate_messages)


make: *** [Makefile:600: cmake_check_build_system] Error 1
